@car_auction_management_HostAddress = http://localhost:5065

GET {{car_auction_management_HostAddress}}/v1/vehicles/55503503-cba2-49b7-8b2e-d1fb05b83584
Accept: application/json

###

POST {{car_auction_management_HostAddress}}/v1/vehicles
Content-Type: application/json
{
    "type": "Sudan",
    "model": "Seal",
    "manufacturer": "BYD",
    "numberOfDoors": 5,
    "StartingPrice": 32000,
    "year": 2024
}